### ISSUE TITLE
No mention of data resolution on docs website

### ISSUE THREAD

**Issue by fortxun** [VividCortex/docs#222]
At the request of Mills, I was unable to find any reference to the granularity of data or retention policies on the docs website. Just a couple of articles on the blog.

**Comment by seaparks** [comment]
It looks like since this was written there's been updates to the docs; these pages mention the 1-second granularity:

https://docs.vividcortex.com/
https://docs.vividcortex.com/how-to-use-vividcortex/how-it-works/
https://docs.vividcortex.com/getting-started/performance/
https://docs.vividcortex.com/how-to-use-vividcortex/graphs/
https://docs.vividcortex.com/how-to-use-vividcortex/profiler/
https://docs.vividcortex.com/general-reference/metric-categories/

I'll add the standard retention policy to the website somewhere, because customer support has gotten questions about it.

**Comment by seaparks** [comment]
Closed with https://github.com/VividCortex/docs/pull/274/
